package spec

// Classes is the registry of ECHONET Lite device object classes.
// Source: ECHONET Lite Appendix Release R (echonet.jp)
var Classes = []DeviceClass{
	{
		GroupCode:   0x0E,
		ClassCode:   0xF0,
		NameJP:      "ノードプロファイル",
		NameEN:      "Node Profile",
		Description: "ECHONET Liteノード自身を表すプロファイルオブジェクト。ネットワーク上の全ノードが必ず持つ。",
		EPCs: []EPCDef{
			{0xBF, "個体識別番号", "Individual identification number", "unsigned char[17]", "", "Set/Get", ""},
			{0xD3, "自ノードインスタンス数", "Number of self-node instances", "unsigned char[3]", "", "Get", ""},
			{0xD4, "自ノードクラス数", "Number of self-node classes", "unsigned char[2]", "", "Get", ""},
			{0xD5, "インスタンスリスト通知", "Instance list notification", "unsigned char[MAX 253]", "", "Anno", ""},
			{0xD6, "自ノードインスタンスリストS", "Self-node instance list S", "unsigned char[MAX 253]", "", "Get", "保有するインスタンスのEOJ一覧"},
			{0xD7, "自ノードクラスリストS", "Self-node class list S", "unsigned char[MAX 253]", "", "Get", ""},
		},
	},
	{
		GroupCode:   0x00,
		ClassCode:   0x11,
		NameJP:      "温度センサ",
		NameEN:      "Temperature Sensor",
		Description: "室内・室外・機器内部などの温度を計測するセンサ。",
		EPCs: []EPCDef{
			{0xE0, "温度計測値", "Measured value of temperature", "short", "0.1°C", "Get", "0x8001〜0x7FFE (-3276.7〜3276.6°C), 0x7FFF=計測不可"},
		},
	},
	{
		GroupCode:   0x00,
		ClassCode:   0x12,
		NameJP:      "湿度センサ",
		NameEN:      "Humidity Sensor",
		Description: "相対湿度を計測するセンサ。",
		EPCs: []EPCDef{
			{0xE0, "相対湿度計測値", "Measured value of relative humidity", "unsigned char", "%", "Get", "0x00〜0x64 (0〜100%), 0xFF=計測不可"},
		},
	},
	{
		GroupCode:   0x00,
		ClassCode:   0x1B,
		NameJP:      "CO2センサ",
		NameEN:      "CO2 Sensor",
		Description: "CO2濃度を計測するセンサ。",
		EPCs: []EPCDef{
			{0xE0, "CO2濃度計測値", "Measured value of CO2 concentration", "unsigned short", "ppm", "Get", "0x0000〜0x2710 (0〜10000ppm)"},
		},
	},
	{
		GroupCode:   0x01,
		ClassCode:   0x30,
		NameJP:      "家庭用エアコン",
		NameEN:      "Home Air Conditioner",
		Description: "家庭用ルームエアコン。冷房・暖房・除湿・送風・自動の運転モードを持つ。",
		EPCs: []EPCDef{
			{0xA0, "風量設定", "Air flow rate setting", "unsigned char", "", "Set/Get", "自動=0x41, 風量1〜8=0x31〜0x38"},
			{0xB0, "運転モード設定", "Operation mode setting", "unsigned char", "", "Set/Get", "自動=0x41, 冷房=0x42, 暖房=0x43, 除湿=0x44, 送風=0x45"},
			{0xB3, "温度設定値", "Temperature setting", "signed char", "°C", "Set/Get", "0x00〜0x32 (0〜50°C)"},
			{0xB4, "除湿モード相対湿度設定値", "Relative humidity setting for dehumidification mode", "unsigned char", "%", "Set/Get", "0x00〜0x64"},
			{0xB5, "冷房モード温度設定値", "Temperature setting for cooling mode", "signed char", "°C", "Set/Get", "0x00〜0x32"},
			{0xB6, "暖房モード温度設定値", "Temperature setting for heating mode", "signed char", "°C", "Set/Get", "0x00〜0x32"},
			{0xB8, "冷房モード定格消費電力値", "Rated power consumption in cooling mode", "unsigned short", "W", "Get", ""},
			{0xB9, "冷房モード電流計測値", "Measured current consumption in cooling mode", "unsigned short", "mA", "Get", ""},
			{0xBA, "室内相対湿度計測値", "Measured value of room relative humidity", "unsigned char", "%", "Get", "0x00〜0x64"},
			{0xBB, "室内温度計測値", "Measured value of room temperature", "signed char", "°C", "Get", "-127〜125°C"},
			{0xBC, "冷房モード温度設定値2", "Temperature setting for cooling mode 2", "unsigned char[2]", "0.1°C", "Set/Get", ""},
			{0xBE, "定格消費電力値", "Rated power consumption", "unsigned short[4]", "W", "Get", "冷房/暖房/除湿/送風の順"},
			{0xC0, "OFFタイマ予約設定", "Off timer reservation setting", "unsigned char", "", "Set/Get", "予約あり=0x41, なし=0x42"},
			{0xC2, "OFFタイマ設定値(時間)", "Off timer setting (time)", "unsigned char[2]", "", "Set/Get", "HH MM"},
			{0xC4, "ONタイマ予約設定", "On timer reservation setting", "unsigned char", "", "Set/Get", "予約あり=0x41, なし=0x42"},
			{0xC5, "ONタイマ設定値(時間)", "On timer setting (time)", "unsigned char[2]", "", "Set/Get", "HH MM"},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x6B,
		NameJP:      "電気温水器",
		NameEN:      "Electric Water Heater",
		Description: "電気ヒートポンプ式給湯機を含む電気温水器。",
		EPCs: []EPCDef{
			{0xB0, "沸き上げ中状態", "Boiling status", "unsigned char", "", "Get", "沸き上げ中=0x41, それ以外=0x42"},
			{0xB2, "貯湯温度設定値", "Temperature setting for hot water supply", "unsigned char", "°C", "Set/Get", "0x00〜0x64"},
			{0xB3, "温水温度設定値", "Temperature setting", "unsigned char", "°C", "Set/Get", "0x00〜0x64"},
			{0xE1, "貯湯量計測値", "Measured amount of hot water remaining", "unsigned char", "L", "Get", "0x00〜0x64"},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x79,
		NameJP:      "太陽光発電",
		NameEN:      "Solar Power Generation",
		Description: "住宅用太陽光発電システム。",
		EPCs: []EPCDef{
			{0xA0, "系統連系状態", "System interconnection status", "unsigned char", "", "Get", "系統連系=0x40, 独立=0x41, 連系+独立=0x42"},
			{0xB0, "瞬時発電電力計測値", "Measured instantaneous power generated", "unsigned short", "W", "Get", "0x0000〜0xFFFD"},
			{0xB1, "積算発電電力量計測値", "Measured cumulative amount of electric energy generated", "unsigned long", "0.001 kWh", "Get", ""},
			{0xB3, "発電電力売電瞬時値計測値", "Measured instantaneous power at power selling", "unsigned short", "W", "Get", ""},
			{0xB4, "積算売電電力量計測値", "Measured cumulative amount of electric energy sold", "unsigned long", "0.001 kWh", "Get", ""},
			{0xE0, "瞬時発電電力計測値(拡張)", "Measured instantaneous power generated (extended)", "unsigned long", "W", "Get", ""},
			{0xE1, "積算発電電力量計測値(拡張)", "Measured cumulative electric energy generated (extended)", "unsigned long", "0.001 kWh", "Get", ""},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x7C,
		NameJP:      "燃料電池",
		NameEN:      "Fuel Cell",
		Description: "家庭用燃料電池（エネファーム等）。",
		EPCs: []EPCDef{
			{0xC1, "貯湯槽熱量", "Stored thermal energy in hot water tank", "unsigned short", "Wh", "Get", ""},
			{0xC2, "系統連系状態", "System interconnection status", "unsigned char", "", "Get", "系統連系=0x40, 独立=0x41"},
			{0xC7, "積算売電電力量計測値", "Measured cumulative amount of electric energy sold", "unsigned long", "0.001 kWh", "Get", ""},
			{0xC8, "瞬時発電電力計測値", "Measured instantaneous power generated", "unsigned short", "W", "Get", ""},
			{0xC9, "積算発電電力量計測値", "Measured cumulative amount of electric energy generated", "unsigned long", "0.001 kWh", "Get", ""},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x7D,
		NameJP:      "蓄電池",
		NameEN:      "Storage Battery",
		Description: "定置型リチウムイオン蓄電池システム等。",
		EPCs: []EPCDef{
			{0xA0, "AC実効容量(充電)", "AC effective capacity (charge)", "unsigned long", "Wh", "Get", ""},
			{0xA2, "AC実効容量(放電)", "AC effective capacity (discharge)", "unsigned long", "Wh", "Get", ""},
			{0xA4, "AC充電上限量設定値", "AC charge upper limit setting", "unsigned char", "%", "Set/Get", "0〜100%"},
			{0xA5, "AC放電下限量設定値", "AC discharge lower limit setting", "unsigned char", "%", "Set/Get", "0〜100%"},
			{0xB0, "運転動作状態", "Operation mode setting", "unsigned char", "", "Set/Get", "急速充電=0x41, 充電=0x42, 放電=0x43, 待機=0x44, テスト=0x45, 自動=0x46"},
			{0xC8, "瞬時充放電電力計測値", "Measured instantaneous charge/discharge power", "signed long", "W", "Get", "正=充電, 負=放電"},
			{0xD0, "AC定格電力(充電)", "AC rated power (charge)", "unsigned short", "W", "Get", ""},
			{0xD1, "AC定格電力(放電)", "AC rated power (discharge)", "unsigned short", "W", "Get", ""},
			{0xE4, "蓄電残量3", "Remaining stored electricity 3", "unsigned char", "%", "Get", "0〜100%"},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x7E,
		NameJP:      "EV充放電器",
		NameEN:      "EV Charge/Discharge Equipment",
		Description: "電気自動車（EV）との間で充放電を行う機器（V2H）。",
		EPCs: []EPCDef{
			{0xA0, "車両接続・充放電可否状態", "Vehicle connection and charge/discharge enable/disable status", "unsigned char", "", "Get", "接続/充放電可=0x40〜"},
			{0xC7, "積算放電電力量計測値", "Measured cumulative amount of discharged electric energy", "unsigned long", "0.001 kWh", "Get", ""},
			{0xC8, "瞬時充放電電力計測値", "Measured instantaneous charge/discharge electric power", "signed long", "W", "Get", "正=充電, 負=放電"},
			{0xD0, "AC定格電力(充電)", "AC rated power (charge)", "unsigned short", "W", "Get", ""},
			{0xD1, "AC定格電力(放電)", "AC rated power (discharge)", "unsigned short", "W", "Get", ""},
			{0xE9, "電池残容量3", "Remaining battery capacity 3", "unsigned char", "%", "Get", "0〜100%"},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x87,
		NameJP:      "分電盤メタリング",
		NameEN:      "Distribution Panel Metering",
		Description: "住宅の分電盤に内蔵または接続されたメタリング機器。",
		EPCs: []EPCDef{
			{0xB2, "積算電力量計測値(正方向)", "Measured cumulative amount of electric energy (normal direction)", "unsigned long", "0.001 kWh", "Get", ""},
			{0xB3, "積算電力量計測値(逆方向)", "Measured cumulative amount of electric energy (reverse direction)", "unsigned long", "0.001 kWh", "Get", ""},
			{0xB4, "積算電力量計測値リスト(正方向)", "Measured cumulative amount of electric energy list (normal direction)", "unsigned char[MAX 194]", "0.001 kWh", "Get", "直近30分毎の計測値"},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x88,
		NameJP:      "低圧スマート電力量メータ",
		NameEN:      "Low-Voltage Smart Electric Energy Meter",
		Description: "電力会社設置の低圧スマートメーター（Bルート対応）。",
		EPCs: []EPCDef{
			{0xD3, "積算電力量有効桁数", "Number of effective digits for cumulative amounts of electric energy", "unsigned char", "", "Get", "有効桁数"},
			{0xD7, "積算電力量計測値単位(正逆)", "Unit for cumulative amounts of electric energy (normal and reverse directions)", "unsigned char", "", "Get", "0x00=1kWh, 0x01=0.1kWh, ... 0x04=0.0001kWh"},
			{0xE0, "積算電力量計測値(正方向)", "Measured cumulative amount of electric energy (normal direction)", "unsigned long", "kWh×単位", "Get", ""},
			{0xE1, "積算電力量計測値単位(正方向)", "Unit for cumulative amounts of electric energy (normal direction)", "unsigned char", "", "Get", ""},
			{0xE3, "積算電力量計測値(逆方向)", "Measured cumulative amount of electric energy (reverse direction)", "unsigned long", "kWh×単位", "Get", ""},
			{0xE7, "瞬時電力計測値", "Measured instantaneous electric power", "signed long", "W", "Get", "正=消費, 負=発電"},
			{0xE8, "瞬時電流計測値", "Measured instantaneous currents", "short[2]", "0.1A", "Get", "R相・T相"},
			{0xEA, "定時積算電力量計測値(正方向)", "Cumulative amounts of electric energy at fixed time (normal direction)", "unsigned char[11]", "", "Get", "年月日時分+電力量"},
			{0xEB, "定時積算電力量計測値(逆方向)", "Cumulative amounts of electric energy at fixed time (reverse direction)", "unsigned char[11]", "", "Get", "年月日時分+電力量"},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0x90,
		NameJP:      "一般照明",
		NameEN:      "General Lighting",
		Description: "LED照明・蛍光灯等の一般照明機器。",
		EPCs: []EPCDef{
			{0xB0, "照度レベル設定", "Illuminance level setting", "unsigned char", "%", "Set/Get", "0〜100%"},
			{0xB1, "光色設定", "Light color setting", "unsigned char", "", "Set/Get", "その他=0x40, 電球色=0x41, 白色=0x42, 昼白色=0x43, 昼光色=0x44"},
			{0xB2, "照度レベル設定(昼間)", "Illuminance level setting for daytime", "unsigned char", "%", "Set/Get", ""},
			{0xB3, "照度レベル設定(夜間)", "Illuminance level setting for nighttime", "unsigned char", "%", "Set/Get", ""},
		},
	},
	{
		GroupCode:   0x02,
		ClassCode:   0xA1,
		NameJP:      "EV充電器",
		NameEN:      "EV Charger",
		Description: "電気自動車（EV）への充電のみ行う機器（V2H非対応）。",
		EPCs: []EPCDef{
			{0xA0, "車両接続確認", "Vehicle connection confirmation", "unsigned char", "", "Get", "接続=0x41, 未接続=0x42"},
			{0xC7, "積算充電電力量計測値", "Measured cumulative amount of charged electric energy", "unsigned long", "0.001 kWh", "Get", ""},
			{0xC8, "瞬時充電電力計測値", "Measured instantaneous charging electric power", "unsigned long", "W", "Get", ""},
			{0xD0, "定格充電電力", "Rated charging power", "unsigned short", "W", "Get", ""},
		},
	},
}
